import { TickerInfo, MarketType } from './types';

// ============================================
// S&P 500 STOCKS (All 500)
// ============================================
const SP500_STOCKS: TickerInfo[] = [
  // Technology
  { symbol: 'AAPL', name: 'Apple Inc.', type: 'stocks' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', type: 'stocks' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. Class A', type: 'stocks' },
  { symbol: 'GOOG', name: 'Alphabet Inc. Class C', type: 'stocks' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', type: 'stocks' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', type: 'stocks' },
  { symbol: 'META', name: 'Meta Platforms Inc.', type: 'stocks' },
  { symbol: 'TSLA', name: 'Tesla Inc.', type: 'stocks' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', type: 'stocks' },
  { symbol: 'ORCL', name: 'Oracle Corporation', type: 'stocks' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', type: 'stocks' },
  { symbol: 'CRM', name: 'Salesforce Inc.', type: 'stocks' },
  { symbol: 'ACN', name: 'Accenture plc', type: 'stocks' },
  { symbol: 'IBM', name: 'International Business Machines', type: 'stocks' },
  { symbol: 'INTC', name: 'Intel Corporation', type: 'stocks' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', type: 'stocks' },
  { symbol: 'QCOM', name: 'QUALCOMM Incorporated', type: 'stocks' },
  { symbol: 'TXN', name: 'Texas Instruments', type: 'stocks' },
  { symbol: 'NOW', name: 'ServiceNow Inc.', type: 'stocks' },
  { symbol: 'INTU', name: 'Intuit Inc.', type: 'stocks' },
  { symbol: 'AMAT', name: 'Applied Materials', type: 'stocks' },
  { symbol: 'ADI', name: 'Analog Devices Inc.', type: 'stocks' },
  { symbol: 'LRCX', name: 'Lam Research Corporation', type: 'stocks' },
  { symbol: 'MU', name: 'Micron Technology', type: 'stocks' },
  { symbol: 'KLAC', name: 'KLA Corporation', type: 'stocks' },
  { symbol: 'SNPS', name: 'Synopsys Inc.', type: 'stocks' },
  { symbol: 'CDNS', name: 'Cadence Design Systems', type: 'stocks' },
  { symbol: 'ADSK', name: 'Autodesk Inc.', type: 'stocks' },
  { symbol: 'PANW', name: 'Palo Alto Networks', type: 'stocks' },
  { symbol: 'FTNT', name: 'Fortinet Inc.', type: 'stocks' },
  { symbol: 'MCHP', name: 'Microchip Technology', type: 'stocks' },
  { symbol: 'NXPI', name: 'NXP Semiconductors', type: 'stocks' },
  { symbol: 'ON', name: 'ON Semiconductor', type: 'stocks' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise', type: 'stocks' },
  { symbol: 'HPQ', name: 'HP Inc.', type: 'stocks' },
  { symbol: 'KEYS', name: 'Keysight Technologies', type: 'stocks' },
  { symbol: 'CTSH', name: 'Cognizant Technology', type: 'stocks' },
  { symbol: 'IT', name: 'Gartner Inc.', type: 'stocks' },
  { symbol: 'GDDY', name: 'GoDaddy Inc.', type: 'stocks' },
  { symbol: 'GEN', name: 'Gen Digital Inc.', type: 'stocks' },
  { symbol: 'FFIV', name: 'F5 Inc.', type: 'stocks' },
  { symbol: 'JNPR', name: 'Juniper Networks', type: 'stocks' },
  { symbol: 'AKAM', name: 'Akamai Technologies', type: 'stocks' },
  { symbol: 'EPAM', name: 'EPAM Systems Inc.', type: 'stocks' },
  { symbol: 'SWKS', name: 'Skyworks Solutions', type: 'stocks' },
  { symbol: 'TER', name: 'Teradyne Inc.', type: 'stocks' },
  { symbol: 'ZBRA', name: 'Zebra Technologies', type: 'stocks' },
  { symbol: 'TRMB', name: 'Trimble Inc.', type: 'stocks' },
  { symbol: 'PTC', name: 'PTC Inc.', type: 'stocks' },
  { symbol: 'PAYC', name: 'Paycom Software', type: 'stocks' },
  // Healthcare
  { symbol: 'UNH', name: 'UnitedHealth Group', type: 'stocks' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', type: 'stocks' },
  { symbol: 'LLY', name: 'Eli Lilly and Company', type: 'stocks' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.', type: 'stocks' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', type: 'stocks' },
  { symbol: 'PFE', name: 'Pfizer Inc.', type: 'stocks' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific', type: 'stocks' },
  { symbol: 'ABT', name: 'Abbott Laboratories', type: 'stocks' },
  { symbol: 'DHR', name: 'Danaher Corporation', type: 'stocks' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', type: 'stocks' },
  { symbol: 'AMGN', name: 'Amgen Inc.', type: 'stocks' },
  { symbol: 'MDT', name: 'Medtronic plc', type: 'stocks' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', type: 'stocks' },
  { symbol: 'GILD', name: 'Gilead Sciences', type: 'stocks' },
  { symbol: 'CVS', name: 'CVS Health Corporation', type: 'stocks' },
  { symbol: 'ELV', name: 'Elevance Health', type: 'stocks' },
  { symbol: 'SYK', name: 'Stryker Corporation', type: 'stocks' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', type: 'stocks' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', type: 'stocks' },
  { symbol: 'BSX', name: 'Boston Scientific', type: 'stocks' },
  { symbol: 'ZTS', name: 'Zoetis Inc.', type: 'stocks' },
  { symbol: 'CI', name: 'Cigna Group', type: 'stocks' },
  { symbol: 'HUM', name: 'Humana Inc.', type: 'stocks' },
  { symbol: 'HCA', name: 'HCA Healthcare', type: 'stocks' },
  { symbol: 'MCK', name: 'McKesson Corporation', type: 'stocks' },
  { symbol: 'EW', name: 'Edwards Lifesciences', type: 'stocks' },
  { symbol: 'BDX', name: 'Becton Dickinson', type: 'stocks' },
  { symbol: 'IQV', name: 'IQVIA Holdings', type: 'stocks' },
  { symbol: 'A', name: 'Agilent Technologies', type: 'stocks' },
  { symbol: 'GEHC', name: 'GE HealthCare', type: 'stocks' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories', type: 'stocks' },
  { symbol: 'BIIB', name: 'Biogen Inc.', type: 'stocks' },
  { symbol: 'MTD', name: 'Mettler-Toledo', type: 'stocks' },
  { symbol: 'DXCM', name: 'DexCom Inc.', type: 'stocks' },
  { symbol: 'CAH', name: 'Cardinal Health', type: 'stocks' },
  { symbol: 'COR', name: 'Cencora Inc.', type: 'stocks' },
  { symbol: 'HOLX', name: 'Hologic Inc.', type: 'stocks' },
  { symbol: 'ALGN', name: 'Align Technology', type: 'stocks' },
  { symbol: 'RMD', name: 'ResMed Inc.', type: 'stocks' },
  { symbol: 'ZBH', name: 'Zimmer Biomet', type: 'stocks' },
  { symbol: 'WAT', name: 'Waters Corporation', type: 'stocks' },
  { symbol: 'ILMN', name: 'Illumina Inc.', type: 'stocks' },
  { symbol: 'PODD', name: 'Insulet Corporation', type: 'stocks' },
  { symbol: 'MOH', name: 'Molina Healthcare', type: 'stocks' },
  { symbol: 'RVTY', name: 'Revvity Inc.', type: 'stocks' },
  { symbol: 'CRL', name: 'Charles River Labs', type: 'stocks' },
  { symbol: 'VTRS', name: 'Viatris Inc.', type: 'stocks' },
  { symbol: 'TECH', name: 'Bio-Techne Corporation', type: 'stocks' },
  { symbol: 'INCY', name: 'Incyte Corporation', type: 'stocks' },
  { symbol: 'DGX', name: 'Quest Diagnostics', type: 'stocks' },
  // Financials
  { symbol: 'BRK.B', name: 'Berkshire Hathaway B', type: 'stocks' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', type: 'stocks' },
  { symbol: 'V', name: 'Visa Inc.', type: 'stocks' },
  { symbol: 'MA', name: 'Mastercard Incorporated', type: 'stocks' },
  { symbol: 'BAC', name: 'Bank of America', type: 'stocks' },
  { symbol: 'WFC', name: 'Wells Fargo & Company', type: 'stocks' },
  { symbol: 'GS', name: 'Goldman Sachs Group', type: 'stocks' },
  { symbol: 'MS', name: 'Morgan Stanley', type: 'stocks' },
  { symbol: 'BLK', name: 'BlackRock Inc.', type: 'stocks' },
  { symbol: 'SPGI', name: 'S&P Global Inc.', type: 'stocks' },
  { symbol: 'C', name: 'Citigroup Inc.', type: 'stocks' },
  { symbol: 'AXP', name: 'American Express', type: 'stocks' },
  { symbol: 'SCHW', name: 'Charles Schwab', type: 'stocks' },
  { symbol: 'CB', name: 'Chubb Limited', type: 'stocks' },
  { symbol: 'MMC', name: 'Marsh & McLennan', type: 'stocks' },
  { symbol: 'PGR', name: 'Progressive Corporation', type: 'stocks' },
  { symbol: 'CME', name: 'CME Group Inc.', type: 'stocks' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', type: 'stocks' },
  { symbol: 'AON', name: 'Aon plc', type: 'stocks' },
  { symbol: 'MCO', name: 'Moody\'s Corporation', type: 'stocks' },
  { symbol: 'USB', name: 'U.S. Bancorp', type: 'stocks' },
  { symbol: 'PNC', name: 'PNC Financial Services', type: 'stocks' },
  { symbol: 'TFC', name: 'Truist Financial', type: 'stocks' },
  { symbol: 'AIG', name: 'American International Group', type: 'stocks' },
  { symbol: 'MSCI', name: 'MSCI Inc.', type: 'stocks' },
  { symbol: 'AFL', name: 'Aflac Incorporated', type: 'stocks' },
  { symbol: 'MET', name: 'MetLife Inc.', type: 'stocks' },
  { symbol: 'AJG', name: 'Arthur J. Gallagher', type: 'stocks' },
  { symbol: 'TRV', name: 'Travelers Companies', type: 'stocks' },
  { symbol: 'ALL', name: 'Allstate Corporation', type: 'stocks' },
  { symbol: 'PRU', name: 'Prudential Financial', type: 'stocks' },
  { symbol: 'COF', name: 'Capital One Financial', type: 'stocks' },
  { symbol: 'BK', name: 'Bank of New York Mellon', type: 'stocks' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp', type: 'stocks' },
  { symbol: 'STT', name: 'State Street Corporation', type: 'stocks' },
  { symbol: 'HIG', name: 'Hartford Financial', type: 'stocks' },
  { symbol: 'MTB', name: 'M&T Bank Corporation', type: 'stocks' },
  { symbol: 'WRB', name: 'W. R. Berkley', type: 'stocks' },
  { symbol: 'RF', name: 'Regions Financial', type: 'stocks' },
  { symbol: 'HBAN', name: 'Huntington Bancshares', type: 'stocks' },
  { symbol: 'KEY', name: 'KeyCorp', type: 'stocks' },
  { symbol: 'NTRS', name: 'Northern Trust', type: 'stocks' },
  { symbol: 'CFG', name: 'Citizens Financial', type: 'stocks' },
  { symbol: 'CINF', name: 'Cincinnati Financial', type: 'stocks' },
  { symbol: 'L', name: 'Loews Corporation', type: 'stocks' },
  { symbol: 'RJF', name: 'Raymond James Financial', type: 'stocks' },
  { symbol: 'DFS', name: 'Discover Financial', type: 'stocks' },
  { symbol: 'ACGL', name: 'Arch Capital Group', type: 'stocks' },
  { symbol: 'SYF', name: 'Synchrony Financial', type: 'stocks' },
  { symbol: 'EG', name: 'Everest Group Ltd', type: 'stocks' },
  // Consumer Discretionary
  { symbol: 'HD', name: 'Home Depot Inc.', type: 'stocks' },
  { symbol: 'MCD', name: 'McDonald\'s Corporation', type: 'stocks' },
  { symbol: 'NKE', name: 'Nike Inc.', type: 'stocks' },
  { symbol: 'SBUX', name: 'Starbucks Corporation', type: 'stocks' },
  { symbol: 'TJX', name: 'TJX Companies Inc.', type: 'stocks' },
  { symbol: 'LOW', name: 'Lowe\'s Companies', type: 'stocks' },
  { symbol: 'BKNG', name: 'Booking Holdings', type: 'stocks' },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill', type: 'stocks' },
  { symbol: 'ORLY', name: 'O\'Reilly Automotive', type: 'stocks' },
  { symbol: 'MAR', name: 'Marriott International', type: 'stocks' },
  { symbol: 'AZO', name: 'AutoZone Inc.', type: 'stocks' },
  { symbol: 'HLT', name: 'Hilton Worldwide', type: 'stocks' },
  { symbol: 'ROST', name: 'Ross Stores Inc.', type: 'stocks' },
  { symbol: 'YUM', name: 'Yum! Brands Inc.', type: 'stocks' },
  { symbol: 'GM', name: 'General Motors Company', type: 'stocks' },
  { symbol: 'F', name: 'Ford Motor Company', type: 'stocks' },
  { symbol: 'DHI', name: 'D.R. Horton Inc.', type: 'stocks' },
  { symbol: 'LEN', name: 'Lennar Corporation', type: 'stocks' },
  { symbol: 'GRMN', name: 'Garmin Ltd.', type: 'stocks' },
  { symbol: 'PHM', name: 'PulteGroup Inc.', type: 'stocks' },
  { symbol: 'NVR', name: 'NVR Inc.', type: 'stocks' },
  { symbol: 'ULTA', name: 'Ulta Beauty Inc.', type: 'stocks' },
  { symbol: 'LVS', name: 'Las Vegas Sands', type: 'stocks' },
  { symbol: 'DRI', name: 'Darden Restaurants', type: 'stocks' },
  { symbol: 'EXPE', name: 'Expedia Group', type: 'stocks' },
  { symbol: 'WYNN', name: 'Wynn Resorts', type: 'stocks' },
  { symbol: 'CCL', name: 'Carnival Corporation', type: 'stocks' },
  { symbol: 'RCL', name: 'Royal Caribbean', type: 'stocks' },
  { symbol: 'NCLH', name: 'Norwegian Cruise Line', type: 'stocks' },
  { symbol: 'DECK', name: 'Deckers Outdoor', type: 'stocks' },
  { symbol: 'GPC', name: 'Genuine Parts Company', type: 'stocks' },
  { symbol: 'POOL', name: 'Pool Corporation', type: 'stocks' },
  { symbol: 'BBY', name: 'Best Buy Co. Inc.', type: 'stocks' },
  { symbol: 'LKQ', name: 'LKQ Corporation', type: 'stocks' },
  { symbol: 'BWA', name: 'BorgWarner Inc.', type: 'stocks' },
  { symbol: 'MGM', name: 'MGM Resorts', type: 'stocks' },
  { symbol: 'TPR', name: 'Tapestry Inc.', type: 'stocks' },
  { symbol: 'CZR', name: 'Caesars Entertainment', type: 'stocks' },
  { symbol: 'RL', name: 'Ralph Lauren', type: 'stocks' },
  { symbol: 'HAS', name: 'Hasbro Inc.', type: 'stocks' },
  { symbol: 'APTV', name: 'Aptiv PLC', type: 'stocks' },
  { symbol: 'EBAY', name: 'eBay Inc.', type: 'stocks' },
  { symbol: 'ETSY', name: 'Etsy Inc.', type: 'stocks' },
  { symbol: 'KMX', name: 'CarMax Inc.', type: 'stocks' },
  { symbol: 'WHR', name: 'Whirlpool Corporation', type: 'stocks' },
  { symbol: 'PVH', name: 'PVH Corp.', type: 'stocks' },
  { symbol: 'MHK', name: 'Mohawk Industries', type: 'stocks' },
  { symbol: 'VFC', name: 'V.F. Corporation', type: 'stocks' },
  { symbol: 'NWL', name: 'Newell Brands', type: 'stocks' },
  // Consumer Staples
  { symbol: 'PG', name: 'Procter & Gamble', type: 'stocks' },
  { symbol: 'KO', name: 'Coca-Cola Company', type: 'stocks' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', type: 'stocks' },
  { symbol: 'COST', name: 'Costco Wholesale', type: 'stocks' },
  { symbol: 'WMT', name: 'Walmart Inc.', type: 'stocks' },
  { symbol: 'PM', name: 'Philip Morris', type: 'stocks' },
  { symbol: 'MO', name: 'Altria Group', type: 'stocks' },
  { symbol: 'MDLZ', name: 'Mondelez International', type: 'stocks' },
  { symbol: 'CL', name: 'Colgate-Palmolive', type: 'stocks' },
  { symbol: 'TGT', name: 'Target Corporation', type: 'stocks' },
  { symbol: 'KMB', name: 'Kimberly-Clark', type: 'stocks' },
  { symbol: 'GIS', name: 'General Mills', type: 'stocks' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper', type: 'stocks' },
  { symbol: 'SYY', name: 'Sysco Corporation', type: 'stocks' },
  { symbol: 'STZ', name: 'Constellation Brands', type: 'stocks' },
  { symbol: 'ADM', name: 'Archer-Daniels-Midland', type: 'stocks' },
  { symbol: 'HSY', name: 'Hershey Company', type: 'stocks' },
  { symbol: 'MNST', name: 'Monster Beverage', type: 'stocks' },
  { symbol: 'EL', name: 'Estée Lauder', type: 'stocks' },
  { symbol: 'K', name: 'Kellanova', type: 'stocks' },
  { symbol: 'KR', name: 'Kroger Co.', type: 'stocks' },
  { symbol: 'CHD', name: 'Church & Dwight', type: 'stocks' },
  { symbol: 'CLX', name: 'Clorox Company', type: 'stocks' },
  { symbol: 'SJM', name: 'J.M. Smucker', type: 'stocks' },
  { symbol: 'MKC', name: 'McCormick & Company', type: 'stocks' },
  { symbol: 'CAG', name: 'Conagra Brands', type: 'stocks' },
  { symbol: 'TSN', name: 'Tyson Foods', type: 'stocks' },
  { symbol: 'HRL', name: 'Hormel Foods', type: 'stocks' },
  { symbol: 'BG', name: 'Bunge Limited', type: 'stocks' },
  { symbol: 'LW', name: 'Lamb Weston', type: 'stocks' },
  { symbol: 'TAP', name: 'Molson Coors', type: 'stocks' },
  { symbol: 'CPB', name: 'Campbell Soup', type: 'stocks' },
  // Industrials
  { symbol: 'CAT', name: 'Caterpillar Inc.', type: 'stocks' },
  { symbol: 'RTX', name: 'RTX Corporation', type: 'stocks' },
  { symbol: 'GE', name: 'General Electric', type: 'stocks' },
  { symbol: 'BA', name: 'Boeing Company', type: 'stocks' },
  { symbol: 'HON', name: 'Honeywell International', type: 'stocks' },
  { symbol: 'UPS', name: 'United Parcel Service', type: 'stocks' },
  { symbol: 'DE', name: 'Deere & Company', type: 'stocks' },
  { symbol: 'LMT', name: 'Lockheed Martin', type: 'stocks' },
  { symbol: 'UNP', name: 'Union Pacific', type: 'stocks' },
  { symbol: 'ETN', name: 'Eaton Corporation', type: 'stocks' },
  { symbol: 'GD', name: 'General Dynamics', type: 'stocks' },
  { symbol: 'NOC', name: 'Northrop Grumman', type: 'stocks' },
  { symbol: 'MMM', name: '3M Company', type: 'stocks' },
  { symbol: 'ITW', name: 'Illinois Tool Works', type: 'stocks' },
  { symbol: 'WM', name: 'Waste Management', type: 'stocks' },
  { symbol: 'EMR', name: 'Emerson Electric', type: 'stocks' },
  { symbol: 'FDX', name: 'FedEx Corporation', type: 'stocks' },
  { symbol: 'NSC', name: 'Norfolk Southern', type: 'stocks' },
  { symbol: 'CSX', name: 'CSX Corporation', type: 'stocks' },
  { symbol: 'PH', name: 'Parker-Hannifin', type: 'stocks' },
  { symbol: 'JCI', name: 'Johnson Controls', type: 'stocks' },
  { symbol: 'PCAR', name: 'PACCAR Inc.', type: 'stocks' },
  { symbol: 'TT', name: 'Trane Technologies', type: 'stocks' },
  { symbol: 'CARR', name: 'Carrier Global', type: 'stocks' },
  { symbol: 'CTAS', name: 'Cintas Corporation', type: 'stocks' },
  { symbol: 'OTIS', name: 'Otis Worldwide', type: 'stocks' },
  { symbol: 'CMI', name: 'Cummins Inc.', type: 'stocks' },
  { symbol: 'LHX', name: 'L3Harris Technologies', type: 'stocks' },
  { symbol: 'ROK', name: 'Rockwell Automation', type: 'stocks' },
  { symbol: 'AME', name: 'AMETEK Inc.', type: 'stocks' },
  { symbol: 'FAST', name: 'Fastenal Company', type: 'stocks' },
  { symbol: 'VRSK', name: 'Verisk Analytics', type: 'stocks' },
  { symbol: 'GWW', name: 'W.W. Grainger', type: 'stocks' },
  { symbol: 'ODFL', name: 'Old Dominion Freight', type: 'stocks' },
  { symbol: 'RSG', name: 'Republic Services', type: 'stocks' },
  { symbol: 'IR', name: 'Ingersoll Rand', type: 'stocks' },
  { symbol: 'PWR', name: 'Quanta Services', type: 'stocks' },
  { symbol: 'PAYX', name: 'Paychex Inc.', type: 'stocks' },
  { symbol: 'XYL', name: 'Xylem Inc.', type: 'stocks' },
  { symbol: 'DOV', name: 'Dover Corporation', type: 'stocks' },
  { symbol: 'HWM', name: 'Howmet Aerospace', type: 'stocks' },
  { symbol: 'CPRT', name: 'Copart Inc.', type: 'stocks' },
  { symbol: 'HUBB', name: 'Hubbell Incorporated', type: 'stocks' },
  { symbol: 'IEX', name: 'IDEX Corporation', type: 'stocks' },
  { symbol: 'FTV', name: 'Fortive Corporation', type: 'stocks' },
  { symbol: 'J', name: 'Jacobs Solutions', type: 'stocks' },
  { symbol: 'WAB', name: 'Westinghouse Air Brake', type: 'stocks' },
  { symbol: 'TDG', name: 'TransDigm Group', type: 'stocks' },
  { symbol: 'SWK', name: 'Stanley Black & Decker', type: 'stocks' },
  { symbol: 'EXPD', name: 'Expeditors International', type: 'stocks' },
  { symbol: 'DAY', name: 'Dayforce Inc.', type: 'stocks' },
  // Energy
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', type: 'stocks' },
  { symbol: 'CVX', name: 'Chevron Corporation', type: 'stocks' },
  { symbol: 'COP', name: 'ConocoPhillips', type: 'stocks' },
  { symbol: 'SLB', name: 'Schlumberger Limited', type: 'stocks' },
  { symbol: 'EOG', name: 'EOG Resources', type: 'stocks' },
  { symbol: 'MPC', name: 'Marathon Petroleum', type: 'stocks' },
  { symbol: 'PXD', name: 'Pioneer Natural Resources', type: 'stocks' },
  { symbol: 'VLO', name: 'Valero Energy', type: 'stocks' },
  { symbol: 'PSX', name: 'Phillips 66', type: 'stocks' },
  { symbol: 'OXY', name: 'Occidental Petroleum', type: 'stocks' },
  { symbol: 'WMB', name: 'Williams Companies', type: 'stocks' },
  { symbol: 'KMI', name: 'Kinder Morgan', type: 'stocks' },
  { symbol: 'HES', name: 'Hess Corporation', type: 'stocks' },
  { symbol: 'HAL', name: 'Halliburton Company', type: 'stocks' },
  { symbol: 'DVN', name: 'Devon Energy', type: 'stocks' },
  { symbol: 'FANG', name: 'Diamondback Energy', type: 'stocks' },
  { symbol: 'BKR', name: 'Baker Hughes', type: 'stocks' },
  { symbol: 'OKE', name: 'ONEOK Inc.', type: 'stocks' },
  { symbol: 'CTRA', name: 'Coterra Energy', type: 'stocks' },
  { symbol: 'TRGP', name: 'Targa Resources', type: 'stocks' },
  { symbol: 'EQT', name: 'EQT Corporation', type: 'stocks' },
  { symbol: 'MRO', name: 'Marathon Oil', type: 'stocks' },
  { symbol: 'APA', name: 'APA Corporation', type: 'stocks' },
  // Communications
  { symbol: 'DIS', name: 'Walt Disney Company', type: 'stocks' },
  { symbol: 'NFLX', name: 'Netflix Inc.', type: 'stocks' },
  { symbol: 'CMCSA', name: 'Comcast Corporation', type: 'stocks' },
  { symbol: 'VZ', name: 'Verizon Communications', type: 'stocks' },
  { symbol: 'T', name: 'AT&T Inc.', type: 'stocks' },
  { symbol: 'TMUS', name: 'T-Mobile US', type: 'stocks' },
  { symbol: 'CHTR', name: 'Charter Communications', type: 'stocks' },
  { symbol: 'EA', name: 'Electronic Arts', type: 'stocks' },
  { symbol: 'TTWO', name: 'Take-Two Interactive', type: 'stocks' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery', type: 'stocks' },
  { symbol: 'OMC', name: 'Omnicom Group', type: 'stocks' },
  { symbol: 'IPG', name: 'Interpublic Group', type: 'stocks' },
  { symbol: 'PARA', name: 'Paramount Global', type: 'stocks' },
  { symbol: 'FOX', name: 'Fox Corporation', type: 'stocks' },
  { symbol: 'FOXA', name: 'Fox Corporation Class A', type: 'stocks' },
  { symbol: 'LYV', name: 'Live Nation Entertainment', type: 'stocks' },
  { symbol: 'NWSA', name: 'News Corp Class A', type: 'stocks' },
  { symbol: 'NWS', name: 'News Corp Class B', type: 'stocks' },
  { symbol: 'MTCH', name: 'Match Group', type: 'stocks' },
  // Utilities
  { symbol: 'NEE', name: 'NextEra Energy', type: 'stocks' },
  { symbol: 'DUK', name: 'Duke Energy', type: 'stocks' },
  { symbol: 'SO', name: 'Southern Company', type: 'stocks' },
  { symbol: 'D', name: 'Dominion Energy', type: 'stocks' },
  { symbol: 'SRE', name: 'Sempra Energy', type: 'stocks' },
  { symbol: 'AEP', name: 'American Electric Power', type: 'stocks' },
  { symbol: 'EXC', name: 'Exelon Corporation', type: 'stocks' },
  { symbol: 'XEL', name: 'Xcel Energy', type: 'stocks' },
  { symbol: 'CEG', name: 'Constellation Energy', type: 'stocks' },
  { symbol: 'PEG', name: 'Public Service Enterprise', type: 'stocks' },
  { symbol: 'ED', name: 'Consolidated Edison', type: 'stocks' },
  { symbol: 'WEC', name: 'WEC Energy Group', type: 'stocks' },
  { symbol: 'EIX', name: 'Edison International', type: 'stocks' },
  { symbol: 'AWK', name: 'American Water Works', type: 'stocks' },
  { symbol: 'ETR', name: 'Entergy Corporation', type: 'stocks' },
  { symbol: 'DTE', name: 'DTE Energy', type: 'stocks' },
  { symbol: 'AEE', name: 'Ameren Corporation', type: 'stocks' },
  { symbol: 'FE', name: 'FirstEnergy Corp', type: 'stocks' },
  { symbol: 'PPL', name: 'PPL Corporation', type: 'stocks' },
  { symbol: 'ES', name: 'Eversource Energy', type: 'stocks' },
  { symbol: 'CMS', name: 'CMS Energy', type: 'stocks' },
  { symbol: 'CNP', name: 'CenterPoint Energy', type: 'stocks' },
  { symbol: 'LNT', name: 'Alliant Energy', type: 'stocks' },
  { symbol: 'NI', name: 'NiSource Inc.', type: 'stocks' },
  { symbol: 'EVRG', name: 'Evergy Inc.', type: 'stocks' },
  { symbol: 'NRG', name: 'NRG Energy', type: 'stocks' },
  { symbol: 'ATO', name: 'Atmos Energy', type: 'stocks' },
  { symbol: 'PNW', name: 'Pinnacle West Capital', type: 'stocks' },
  // Materials
  { symbol: 'LIN', name: 'Linde plc', type: 'stocks' },
  { symbol: 'APD', name: 'Air Products', type: 'stocks' },
  { symbol: 'SHW', name: 'Sherwin-Williams', type: 'stocks' },
  { symbol: 'FCX', name: 'Freeport-McMoRan', type: 'stocks' },
  { symbol: 'ECL', name: 'Ecolab Inc.', type: 'stocks' },
  { symbol: 'NUE', name: 'Nucor Corporation', type: 'stocks' },
  { symbol: 'DD', name: 'DuPont de Nemours', type: 'stocks' },
  { symbol: 'CTVA', name: 'Corteva Inc.', type: 'stocks' },
  { symbol: 'DOW', name: 'Dow Inc.', type: 'stocks' },
  { symbol: 'PPG', name: 'PPG Industries', type: 'stocks' },
  { symbol: 'NEM', name: 'Newmont Corporation', type: 'stocks' },
  { symbol: 'VMC', name: 'Vulcan Materials', type: 'stocks' },
  { symbol: 'MLM', name: 'Martin Marietta', type: 'stocks' },
  { symbol: 'IFF', name: 'International Flavors', type: 'stocks' },
  { symbol: 'ALB', name: 'Albemarle Corporation', type: 'stocks' },
  { symbol: 'CF', name: 'CF Industries', type: 'stocks' },
  { symbol: 'BALL', name: 'Ball Corporation', type: 'stocks' },
  { symbol: 'AVY', name: 'Avery Dennison', type: 'stocks' },
  { symbol: 'FMC', name: 'FMC Corporation', type: 'stocks' },
  { symbol: 'CE', name: 'Celanese Corporation', type: 'stocks' },
  { symbol: 'PKG', name: 'Packaging Corp of America', type: 'stocks' },
  { symbol: 'IP', name: 'International Paper', type: 'stocks' },
  { symbol: 'STLD', name: 'Steel Dynamics', type: 'stocks' },
  { symbol: 'MOS', name: 'Mosaic Company', type: 'stocks' },
  { symbol: 'AMCR', name: 'Amcor plc', type: 'stocks' },
  { symbol: 'WRK', name: 'WestRock Company', type: 'stocks' },
  // Real Estate
  { symbol: 'PLD', name: 'Prologis Inc.', type: 'stocks' },
  { symbol: 'AMT', name: 'American Tower', type: 'stocks' },
  { symbol: 'EQIX', name: 'Equinix Inc.', type: 'stocks' },
  { symbol: 'CCI', name: 'Crown Castle', type: 'stocks' },
  { symbol: 'PSA', name: 'Public Storage', type: 'stocks' },
  { symbol: 'SPG', name: 'Simon Property Group', type: 'stocks' },
  { symbol: 'O', name: 'Realty Income', type: 'stocks' },
  { symbol: 'DLR', name: 'Digital Realty', type: 'stocks' },
  { symbol: 'WELL', name: 'Welltower Inc.', type: 'stocks' },
  { symbol: 'AVB', name: 'AvalonBay Communities', type: 'stocks' },
  { symbol: 'EQR', name: 'Equity Residential', type: 'stocks' },
  { symbol: 'VICI', name: 'VICI Properties', type: 'stocks' },
  { symbol: 'WY', name: 'Weyerhaeuser Company', type: 'stocks' },
  { symbol: 'VTR', name: 'Ventas Inc.', type: 'stocks' },
  { symbol: 'ARE', name: 'Alexandria Real Estate', type: 'stocks' },
  { symbol: 'EXR', name: 'Extra Space Storage', type: 'stocks' },
  { symbol: 'IRM', name: 'Iron Mountain', type: 'stocks' },
  { symbol: 'MAA', name: 'Mid-America Apartment', type: 'stocks' },
  { symbol: 'ESS', name: 'Essex Property Trust', type: 'stocks' },
  { symbol: 'SBAC', name: 'SBA Communications', type: 'stocks' },
  { symbol: 'UDR', name: 'UDR Inc.', type: 'stocks' },
  { symbol: 'INVH', name: 'Invitation Homes', type: 'stocks' },
  { symbol: 'SUI', name: 'Sun Communities', type: 'stocks' },
  { symbol: 'BXP', name: 'BXP Inc.', type: 'stocks' },
  { symbol: 'KIM', name: 'Kimco Realty', type: 'stocks' },
  { symbol: 'REG', name: 'Regency Centers', type: 'stocks' },
  { symbol: 'CPT', name: 'Camden Property Trust', type: 'stocks' },
  { symbol: 'HST', name: 'Host Hotels & Resorts', type: 'stocks' },
  { symbol: 'FRT', name: 'Federal Realty', type: 'stocks' },
  { symbol: 'PEAK', name: 'Healthpeak Properties', type: 'stocks' },
];

// ============================================
// NASDAQ-100 (Non-overlapping with S&P 500)
// ============================================
const NASDAQ100_UNIQUE: TickerInfo[] = [
  { symbol: 'ABNB', name: 'Airbnb Inc.', type: 'stocks' },
  { symbol: 'AEP', name: 'American Electric Power', type: 'stocks' },
  { symbol: 'ANSS', name: 'ANSYS Inc.', type: 'stocks' },
  { symbol: 'ARM', name: 'Arm Holdings', type: 'stocks' },
  { symbol: 'ASML', name: 'ASML Holding', type: 'stocks' },
  { symbol: 'AZN', name: 'AstraZeneca', type: 'stocks' },
  { symbol: 'BKR', name: 'Baker Hughes', type: 'stocks' },
  { symbol: 'CCEP', name: 'Coca-Cola Europacific', type: 'stocks' },
  { symbol: 'CDW', name: 'CDW Corporation', type: 'stocks' },
  { symbol: 'CEG', name: 'Constellation Energy', type: 'stocks' },
  { symbol: 'COIN', name: 'Coinbase Global', type: 'stocks' },
  { symbol: 'CPNG', name: 'Coupang Inc.', type: 'stocks' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings', type: 'stocks' },
  { symbol: 'CSX', name: 'CSX Corporation', type: 'stocks' },
  { symbol: 'DASH', name: 'DoorDash Inc.', type: 'stocks' },
  { symbol: 'DDOG', name: 'Datadog Inc.', type: 'stocks' },
  { symbol: 'DLTR', name: 'Dollar Tree Inc.', type: 'stocks' },
  { symbol: 'FANG', name: 'Diamondback Energy', type: 'stocks' },
  { symbol: 'FAST', name: 'Fastenal Company', type: 'stocks' },
  { symbol: 'GFS', name: 'GlobalFoundries', type: 'stocks' },
  { symbol: 'HON', name: 'Honeywell International', type: 'stocks' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories', type: 'stocks' },
  { symbol: 'ILMN', name: 'Illumina Inc.', type: 'stocks' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper', type: 'stocks' },
  { symbol: 'KHC', name: 'Kraft Heinz Company', type: 'stocks' },
  { symbol: 'LULU', name: 'Lululemon Athletica', type: 'stocks' },
  { symbol: 'MELI', name: 'MercadoLibre Inc.', type: 'stocks' },
  { symbol: 'MRVL', name: 'Marvell Technology', type: 'stocks' },
  { symbol: 'ODFL', name: 'Old Dominion Freight', type: 'stocks' },
  { symbol: 'PCAR', name: 'PACCAR Inc.', type: 'stocks' },
  { symbol: 'PDD', name: 'PDD Holdings', type: 'stocks' },
  { symbol: 'PYPL', name: 'PayPal Holdings', type: 'stocks' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', type: 'stocks' },
  { symbol: 'ROST', name: 'Ross Stores Inc.', type: 'stocks' },
  { symbol: 'SBUX', name: 'Starbucks Corporation', type: 'stocks' },
  { symbol: 'SMCI', name: 'Super Micro Computer', type: 'stocks' },
  { symbol: 'SNPS', name: 'Synopsys Inc.', type: 'stocks' },
  { symbol: 'TEAM', name: 'Atlassian Corporation', type: 'stocks' },
  { symbol: 'TTWO', name: 'Take-Two Interactive', type: 'stocks' },
  { symbol: 'VRSK', name: 'Verisk Analytics', type: 'stocks' },
  { symbol: 'WDAY', name: 'Workday Inc.', type: 'stocks' },
  { symbol: 'XEL', name: 'Xcel Energy', type: 'stocks' },
  { symbol: 'ZS', name: 'Zscaler Inc.', type: 'stocks' },
];

// ============================================
// TOP 100 CRYPTOCURRENCIES BY MARKET CAP
// ============================================
const TOP_100_CRYPTO: TickerInfo[] = [
  { symbol: 'BTCUSD', name: 'Bitcoin', type: 'crypto' },
  { symbol: 'ETHUSD', name: 'Ethereum', type: 'crypto' },
  { symbol: 'XRPUSD', name: 'XRP (Ripple)', type: 'crypto' },
  { symbol: 'SOLUSD', name: 'Solana', type: 'crypto' },
  { symbol: 'BNBUSD', name: 'BNB (Binance Coin)', type: 'crypto' },
  { symbol: 'USDTUSD', name: 'Tether (USDT)', type: 'crypto' },
  { symbol: 'USDCUSD', name: 'USD Coin (USDC)', type: 'crypto' },
  { symbol: 'ADAUSD', name: 'Cardano', type: 'crypto' },
  { symbol: 'DOGEUSD', name: 'Dogecoin', type: 'crypto' },
  { symbol: 'AVAXUSD', name: 'Avalanche', type: 'crypto' },
  { symbol: 'TRXUSD', name: 'TRON', type: 'crypto' },
  { symbol: 'DOTUSD', name: 'Polkadot', type: 'crypto' },
  { symbol: 'LINKUSD', name: 'Chainlink', type: 'crypto' },
  { symbol: 'SHIBUSD', name: 'Shiba Inu', type: 'crypto' },
  { symbol: 'MATICUSD', name: 'Polygon (MATIC)', type: 'crypto' },
  { symbol: 'LTCUSD', name: 'Litecoin', type: 'crypto' },
  { symbol: 'BCHUSD', name: 'Bitcoin Cash', type: 'crypto' },
  { symbol: 'XLMUSD', name: 'Stellar', type: 'crypto' },
  { symbol: 'UNIUSD', name: 'Uniswap', type: 'crypto' },
  { symbol: 'ATOMUSD', name: 'Cosmos', type: 'crypto' },
  { symbol: 'ICPUSD', name: 'Internet Computer', type: 'crypto' },
  { symbol: 'HBARUSD', name: 'Hedera', type: 'crypto' },
  { symbol: 'ETCUSD', name: 'Ethereum Classic', type: 'crypto' },
  { symbol: 'FILUSD', name: 'Filecoin', type: 'crypto' },
  { symbol: 'VETUSD', name: 'VeChain', type: 'crypto' },
  { symbol: 'NEOUSD', name: 'NEO', type: 'crypto' },
  { symbol: 'XMRUSD', name: 'Monero', type: 'crypto' },
  { symbol: 'OPUSD', name: 'Optimism', type: 'crypto' },
  { symbol: 'ARBUSD', name: 'Arbitrum', type: 'crypto' },
  { symbol: 'APTUSD', name: 'Aptos', type: 'crypto' },
  { symbol: 'NEARUSD', name: 'NEAR Protocol', type: 'crypto' },
  { symbol: 'AAVEUSD', name: 'Aave', type: 'crypto' },
  { symbol: 'MKRUSD', name: 'Maker', type: 'crypto' },
  { symbol: 'ALGOUSD', name: 'Algorand', type: 'crypto' },
  { symbol: 'FTMUSD', name: 'Fantom', type: 'crypto' },
  { symbol: 'SANDUSD', name: 'The Sandbox', type: 'crypto' },
  { symbol: 'MANAUSD', name: 'Decentraland', type: 'crypto' },
  { symbol: 'XTZUSD', name: 'Tezos', type: 'crypto' },
  { symbol: 'THETAUSD', name: 'Theta Network', type: 'crypto' },
  { symbol: 'AXSUSD', name: 'Axie Infinity', type: 'crypto' },
  { symbol: 'EOSUSD', name: 'EOS', type: 'crypto' },
  { symbol: 'FLOWUSD', name: 'Flow', type: 'crypto' },
  { symbol: 'SNXUSD', name: 'Synthetix', type: 'crypto' },
  { symbol: 'LRCUSD', name: 'Loopring', type: 'crypto' },
  { symbol: 'ENJUSD', name: 'Enjin Coin', type: 'crypto' },
  { symbol: 'CRVUSD', name: 'Curve DAO', type: 'crypto' },
  { symbol: 'RUNEUSD', name: 'THORChain', type: 'crypto' },
  { symbol: 'GALAUSD', name: 'Gala', type: 'crypto' },
  { symbol: 'APEUSD', name: 'ApeCoin', type: 'crypto' },
  { symbol: '1INCHUSD', name: '1inch Network', type: 'crypto' },
  { symbol: 'COMPUSD', name: 'Compound', type: 'crypto' },
  { symbol: 'ZECUSD', name: 'Zcash', type: 'crypto' },
  { symbol: 'DASHUSD', name: 'Dash', type: 'crypto' },
  { symbol: 'WAVESUSD', name: 'Waves', type: 'crypto' },
  { symbol: 'CHZUSD', name: 'Chiliz', type: 'crypto' },
  { symbol: 'BATUSD', name: 'Basic Attention Token', type: 'crypto' },
  { symbol: 'ZILUSD', name: 'Zilliqa', type: 'crypto' },
  { symbol: 'KAVAUSD', name: 'Kava', type: 'crypto' },
  { symbol: 'GMXUSD', name: 'GMX', type: 'crypto' },
  { symbol: 'DYDXUSD', name: 'dYdX', type: 'crypto' },
  { symbol: 'PEPEUSD', name: 'Pepe', type: 'crypto' },
  { symbol: 'FLOKIUSD', name: 'Floki', type: 'crypto' },
  { symbol: 'SUIUSD', name: 'Sui', type: 'crypto' },
  { symbol: 'SEIUSD', name: 'Sei', type: 'crypto' },
  { symbol: 'INJUSD', name: 'Injective', type: 'crypto' },
  { symbol: 'STXUSD', name: 'Stacks', type: 'crypto' },
  { symbol: 'IMXUSD', name: 'Immutable X', type: 'crypto' },
  { symbol: 'MINAUSD', name: 'Mina Protocol', type: 'crypto' },
  { symbol: 'TIAUSD', name: 'Celestia', type: 'crypto' },
  { symbol: 'PYTHUSD', name: 'Pyth Network', type: 'crypto' },
  { symbol: 'JUPUSD', name: 'Jupiter', type: 'crypto' },
  { symbol: 'WIFUSD', name: 'dogwifhat', type: 'crypto' },
  { symbol: 'BONKUSD', name: 'Bonk', type: 'crypto' },
  { symbol: 'FETUSD', name: 'Fetch.ai', type: 'crypto' },
  { symbol: 'RNDUSD', name: 'Render', type: 'crypto' },
  { symbol: 'ARUSD', name: 'Arweave', type: 'crypto' },
  { symbol: 'ROSEUSD', name: 'Oasis Network', type: 'crypto' },
  { symbol: 'WLDUSD', name: 'Worldcoin', type: 'crypto' },
  { symbol: 'ENSUSD', name: 'Ethereum Name Service', type: 'crypto' },
  { symbol: 'LDOUSD', name: 'Lido DAO', type: 'crypto' },
  { symbol: 'RPLUSD', name: 'Rocket Pool', type: 'crypto' },
  { symbol: 'CVXUSD', name: 'Convex Finance', type: 'crypto' },
  { symbol: 'GMTUSD', name: 'STEPN', type: 'crypto' },
  { symbol: 'OCEANUSD', name: 'Ocean Protocol', type: 'crypto' },
  { symbol: 'KSMUSD', name: 'Kusama', type: 'crypto' },
  { symbol: 'CELOUSD', name: 'Celo', type: 'crypto' },
  { symbol: 'SKLUSD', name: 'SKALE', type: 'crypto' },
  { symbol: 'ANKRUSD', name: 'Ankr', type: 'crypto' },
  { symbol: 'STORJUSD', name: 'Storj', type: 'crypto' },
  { symbol: 'IOTAUSD', name: 'IOTA', type: 'crypto' },
  { symbol: 'ONTUSD', name: 'Ontology', type: 'crypto' },
  { symbol: 'ICXUSD', name: 'ICON', type: 'crypto' },
  { symbol: 'QTMUSD', name: 'Qtum', type: 'crypto' },
  { symbol: 'RVNUSD', name: 'Ravencoin', type: 'crypto' },
  { symbol: 'SCUSD', name: 'Siacoin', type: 'crypto' },
  { symbol: 'ZENUSD', name: 'Horizen', type: 'crypto' },
  { symbol: 'DGBUSD', name: 'DigiByte', type: 'crypto' },
  { symbol: 'ONDUSD', name: 'Ondo', type: 'crypto' },
  { symbol: 'TONUSD', name: 'Toncoin', type: 'crypto' },
];

// ============================================
// FOREX PAIRS
// ============================================
const FOREX_PAIRS: TickerInfo[] = [
  { symbol: 'EURUSD', name: 'EUR/USD', type: 'forex', baseCurrency: 'EUR', quoteCurrency: 'USD' },
  { symbol: 'GBPUSD', name: 'GBP/USD', type: 'forex', baseCurrency: 'GBP', quoteCurrency: 'USD' },
  { symbol: 'USDJPY', name: 'USD/JPY', type: 'forex', baseCurrency: 'USD', quoteCurrency: 'JPY' },
  { symbol: 'AUDUSD', name: 'AUD/USD', type: 'forex', baseCurrency: 'AUD', quoteCurrency: 'USD' },
  { symbol: 'USDCAD', name: 'USD/CAD', type: 'forex', baseCurrency: 'USD', quoteCurrency: 'CAD' },
  { symbol: 'USDCHF', name: 'USD/CHF', type: 'forex', baseCurrency: 'USD', quoteCurrency: 'CHF' },
  { symbol: 'NZDUSD', name: 'NZD/USD', type: 'forex', baseCurrency: 'NZD', quoteCurrency: 'USD' },
  { symbol: 'EURGBP', name: 'EUR/GBP', type: 'forex', baseCurrency: 'EUR', quoteCurrency: 'GBP' },
  { symbol: 'EURJPY', name: 'EUR/JPY', type: 'forex', baseCurrency: 'EUR', quoteCurrency: 'JPY' },
  { symbol: 'GBPJPY', name: 'GBP/JPY', type: 'forex', baseCurrency: 'GBP', quoteCurrency: 'JPY' },
  { symbol: 'AUDJPY', name: 'AUD/JPY', type: 'forex', baseCurrency: 'AUD', quoteCurrency: 'JPY' },
  { symbol: 'EURAUD', name: 'EUR/AUD', type: 'forex', baseCurrency: 'EUR', quoteCurrency: 'AUD' },
  { symbol: 'EURCHF', name: 'EUR/CHF', type: 'forex', baseCurrency: 'EUR', quoteCurrency: 'CHF' },
  { symbol: 'CADJPY', name: 'CAD/JPY', type: 'forex', baseCurrency: 'CAD', quoteCurrency: 'JPY' },
  { symbol: 'GBPAUD', name: 'GBP/AUD', type: 'forex', baseCurrency: 'GBP', quoteCurrency: 'AUD' },
  { symbol: 'GBPCHF', name: 'GBP/CHF', type: 'forex', baseCurrency: 'GBP', quoteCurrency: 'CHF' },
  { symbol: 'AUDCAD', name: 'AUD/CAD', type: 'forex', baseCurrency: 'AUD', quoteCurrency: 'CAD' },
  { symbol: 'AUDNZD', name: 'AUD/NZD', type: 'forex', baseCurrency: 'AUD', quoteCurrency: 'NZD' },
  { symbol: 'NZDJPY', name: 'NZD/JPY', type: 'forex', baseCurrency: 'NZD', quoteCurrency: 'JPY' },
  { symbol: 'CHFJPY', name: 'CHF/JPY', type: 'forex', baseCurrency: 'CHF', quoteCurrency: 'JPY' },
];

// ============================================
// INDICES
// ============================================
const INDICES: TickerInfo[] = [
  { symbol: 'SPX500', name: 'S&P 500', type: 'indices' },
  { symbol: 'NASDAQ', name: 'NASDAQ 100', type: 'indices' },
  { symbol: 'DJI', name: 'Dow Jones Industrial', type: 'indices' },
  { symbol: 'DAX', name: 'DAX 40', type: 'indices' },
  { symbol: 'FTSE', name: 'FTSE 100', type: 'indices' },
  { symbol: 'NIKKEI', name: 'Nikkei 225', type: 'indices' },
  { symbol: 'CAC40', name: 'CAC 40', type: 'indices' },
  { symbol: 'STOXX50', name: 'Euro Stoxx 50', type: 'indices' },
  { symbol: 'ASX200', name: 'ASX 200', type: 'indices' },
  { symbol: 'HSI', name: 'Hang Seng', type: 'indices' },
  { symbol: 'RUSSELL', name: 'Russell 2000', type: 'indices' },
  { symbol: 'VIX', name: 'VIX Volatility', type: 'indices' },
];

// ============================================
// COMMODITIES
// ============================================
const COMMODITIES: TickerInfo[] = [
  { symbol: 'XAUUSD', name: 'Gold', type: 'commodities' },
  { symbol: 'XAGUSD', name: 'Silver', type: 'commodities' },
  { symbol: 'WTIUSD', name: 'Crude Oil WTI', type: 'commodities' },
  { symbol: 'BRENTUSD', name: 'Brent Crude Oil', type: 'commodities' },
  { symbol: 'NATGAS', name: 'Natural Gas', type: 'commodities' },
  { symbol: 'COPPER', name: 'Copper', type: 'commodities' },
  { symbol: 'PLATINUM', name: 'Platinum', type: 'commodities' },
  { symbol: 'PALLADIUM', name: 'Palladium', type: 'commodities' },
  { symbol: 'WHEAT', name: 'Wheat', type: 'commodities' },
  { symbol: 'CORN', name: 'Corn', type: 'commodities' },
  { symbol: 'SOYBEAN', name: 'Soybeans', type: 'commodities' },
  { symbol: 'COFFEE', name: 'Coffee', type: 'commodities' },
  { symbol: 'SUGAR', name: 'Sugar', type: 'commodities' },
  { symbol: 'COTTON', name: 'Cotton', type: 'commodities' },
];

// ============================================
// COMBINED TICKERS LIST
// ============================================

// Deduplicate by symbol (NASDAQ-100 may overlap with S&P 500)
const deduplicateBySymbol = (tickers: TickerInfo[]): TickerInfo[] => {
  const seen = new Set<string>();
  return tickers.filter(t => {
    if (seen.has(t.symbol)) return false;
    seen.add(t.symbol);
    return true;
  });
};

export const TICKERS: TickerInfo[] = deduplicateBySymbol([
  ...FOREX_PAIRS,
  ...INDICES,
  ...COMMODITIES,
  ...TOP_100_CRYPTO,
  ...SP500_STOCKS,
  ...NASDAQ100_UNIQUE,
]);

// Get tickers by market type
export const getTickersByType = (type: MarketType): TickerInfo[] => {
  return TICKERS.filter(t => t.type === type);
};

// Get ticker by symbol
export const getTickerBySymbol = (symbol: string): TickerInfo | undefined => {
  return TICKERS.find(t => t.symbol === symbol);
};

// Market type labels
export const MARKET_LABELS: Record<MarketType, string> = {
  forex: 'Forex',
  indices: 'Indices',
  commodities: 'Commodities',
  crypto: 'Crypto',
  stocks: 'Stocks',
};

// Stock sector categories (for filtering)
export const STOCK_SECTORS = [
  'Technology',
  'Healthcare',
  'Financials',
  'Consumer Discretionary',
  'Consumer Staples',
  'Industrials',
  'Energy',
  'Communications',
  'Utilities',
  'Materials',
  'Real Estate',
] as const;

// Timeframe labels
export const TIMEFRAME_LABELS: Record<string, string> = {
  '1m': '1 Min',
  '5m': '5 Min',
  '15m': '15 Min',
  '1h': '1 Hour',
  '4h': '4 Hour',
  '1d': 'Daily',
  '1w': 'Weekly',
};

// Tier-based timeframe access
export const TIER_TIMEFRAMES: Record<number, string[]> = {
  1: ['1h'],
  2: ['15m', '1h', '4h'],
  3: ['5m', '15m', '1h', '4h', '1d'],
  4: ['1m', '5m', '15m', '1h', '4h', '1d', '1w'],
  5: ['1m', '5m', '15m', '1h', '4h', '1d', '1w'],
};

// Get ticker counts by category
export const getTickerCounts = () => ({
  forex: getTickersByType('forex').length,
  indices: getTickersByType('indices').length,
  commodities: getTickersByType('commodities').length,
  crypto: getTickersByType('crypto').length,
  stocks: getTickersByType('stocks').length,
  total: TICKERS.length,
});
