// Agent configuration registry
// Centralized definitions for all 10 AI agent models

import { AgentId, StrategyBlockType } from './types';
import { MarketType } from '@/lib/market/types';

export interface AgentDefinition {
  id: AgentId;
  name: string;
  description: string;
  coreStrategy: string;
  market: MarketType;
  model: string;
  icon: string;
  color: string;
  baseWinRate: number;
  baseSharpe: number;
  coordinationScore: number;
  strategyBlocks: StrategyBlockType[];
}

export const ALL_AGENT_IDS: AgentId[] = [
  'equities-alpha',
  'forex-macro',
  'crypto-momentum',
  'liquidity-radar',
  'range-navigator',
  'volatility-architect',
  'adaptive-learner',
  'sentiment-reactor',
  'fractal-intelligence',
  'risk-sentinel',
  // FX Specialists
  'session-momentum',
  'carry-flow',
  'correlation-regime',
  'spread-microstructure',
  'news-event-shield',
  // Cross-Asset Intelligence
  'cross-asset-sync',
  'execution-optimizer',
  'regime-transition',
];

export const AGENT_DEFINITIONS: Record<AgentId, AgentDefinition> = {
  'equities-alpha': {
    id: 'equities-alpha',
    name: 'Alpha Engine',
    description: 'Alpha Engine is QuantLabs\' flagship equities-focused AI, engineered for institutional-grade quantitative analysis across the S&P 500 universe. Alpha Engine views markets as directional energy fields — measuring volatility compression, trend efficiency, and momentum acceleration to isolate high-conviction directional opportunities. It employs ATR-normalized confidence scoring to dynamically size positions based on structural clarity, and uses volatility-compression entry timing to enter trades at optimal inflection points. Alpha Engine is the cornerstone of the multi-agent coordination system, often assuming the Lead AI role due to its superior structural analysis and trend-following precision.',
    coreStrategy: 'Institutional trend-following with momentum overlay. Alpha Engine measures volatility compression for precision entry timing, tracks trend efficiency to distinguish clean directional moves from noise, and uses ATR-normalized confidence for dynamic position sizing. Breakout detection identifies compression zones, while macro overlay adjusts exposure based on cross-market correlation.',
    market: 'stocks',
    model: 'Gemini Pro',
    icon: '📈',
    color: 'text-neural-green',
    baseWinRate: 0.61,
    baseSharpe: 1.6,
    coordinationScore: 78,
    strategyBlocks: ['trend-follow', 'momentum', 'breakout', 'volatility-compression', 'macro-overlay'],
  },
  'forex-macro': {
    id: 'forex-macro',
    name: 'Macro Pulse',
    description: 'Macro Pulse is QuantLabs\' high-frequency forex scalping AI, engineered for rapid-fire execution across major currency pairs on OANDA. Macro Pulse views FX markets as continuous micro-opportunity streams — exploiting session-specific liquidity surges, tight-spread windows, and sub-15-minute momentum pulses to generate high-volume trade flow. It combines macro regime awareness with scalping precision, prioritizing trade count and capital velocity over individual trade size. Macro Pulse thrives during London/NY overlap sessions where liquidity depth enables maximum scalp frequency with minimal slippage.',
    coreStrategy: 'High-volume scalping with macro session awareness. Macro Pulse targets 1-15 minute trade windows on major pairs, using spread stability detection for entry timing, ATR-micro confidence for rapid position sizing, and session-optimized aggression scaling. Trades are designed for quick capture and fast exit — volume over magnitude. Anti-overtrading governors prevent degradation during low-liquidity windows.',
    market: 'forex',
    model: 'GPT-5',
    icon: '🌐',
    color: 'text-primary',
    baseWinRate: 0.64,
    baseSharpe: 1.55,
    coordinationScore: 78,
    strategyBlocks: ['momentum', 'breakout', 'volatility-compression', 'trend-follow', 'macro-overlay'],
  },
  'crypto-momentum': {
    id: 'crypto-momentum',
    name: 'Momentum Grid',
    description: 'Momentum Grid is QuantLabs\' crypto-focused AI, purpose-built for the 24/7 digital asset markets where volatility is the dominant market feature. Momentum Grid views cryptocurrency markets as high-energy momentum systems — where explosive directional moves emerge from volatility compression phases, and conviction acceleration separates genuine breakouts from liquidation-driven noise. It specializes in detecting the transition from low-volatility squeeze setups to high-expansion moves, using ATR-based conviction scaling optimized for the extreme volatility environment of digital assets.',
    coreStrategy: 'Alpha Engine-calibrated momentum-first strategy with volatility compression detection. Momentum Grid identifies squeeze setups for early entry in explosive moves, tracks trend efficiency to filter genuine directional conviction from liquidation cascade noise, and scales positions via ATR-normalized confidence. Optimized for crypto\'s 24/7 market structure with enhanced sensitivity to rapid regime transitions.',
    market: 'crypto',
    model: 'Gemini Flash',
    icon: '⚡',
    color: 'text-neural-orange',
    baseWinRate: 0.55,
    baseSharpe: 1.3,
    coordinationScore: 68,
    strategyBlocks: ['trend-follow', 'momentum', 'breakout', 'volatility-compression', 'macro-overlay'],
  },
  'liquidity-radar': {
    id: 'liquidity-radar',
    name: 'Liquidity Radar',
    description: 'Liquidity Radar is QuantLabs\' FX order flow and liquidity mapping engine, optimized to support high-frequency scalping by detecting micro-liquidity pockets, stop-hunt zones, and spread widening events in real-time. Liquidity Radar scans bid/ask depth across OANDA-compatible pairs to identify optimal scalp entry windows where spread-to-move ratios are most favorable. It prevents the scalping fleet from entering trades into liquidity traps or during spread blow-outs, directly improving scalp capture rates and reducing friction-based losses.',
    coreStrategy: 'Micro-liquidity analysis for scalping optimization. Liquidity Radar detects stop-hunt probability zones at scalping timeframes, maps spread stability windows for optimal entry timing, and tracks order flow imbalances that signal 1-5 minute directional micro-moves. Price magnet zone mapping at scalp scale identifies where quick fills and tight exits are most probable.',
    market: 'forex',
    model: 'Claude 3.5',
    icon: '🌀',
    color: 'text-cyan-400',
    baseWinRate: 0.61,
    baseSharpe: 1.50,
    coordinationScore: 76,
    strategyBlocks: ['breakout', 'momentum', 'range-trading', 'volatility-compression', 'macro-overlay'],
  },
  'range-navigator': {
    id: 'range-navigator',
    name: 'Range Navigator',
    description: 'Range Navigator is QuantLabs\' FX range-scalping specialist, purpose-built for high-frequency mean-reversion scalps within identified equilibrium zones. Range Navigator detects micro-range boundaries on major pairs and executes rapid fade trades at range extremes — buying support bounces and selling resistance rejections in sub-10-minute windows. It provides critical counterbalance to momentum scalps by capturing rotational flow during consolidation phases, ensuring the fleet maintains high trade volume even in non-trending conditions.',
    coreStrategy: 'High-frequency range-fade scalping with boundary elasticity timing. Range Navigator identifies micro-consolidation structures on 1-5 minute timeframes, executes mean-reversion scalps at statistical boundaries, and exits within 2-12 minutes. Oscillation amplitude modeling predicts rotation distance for precise take-profit placement, while session-aware aggression prevents fade scalps during breakout-prone windows.',
    market: 'forex',
    model: 'GPT-4o',
    icon: '🧭',
    color: 'text-amber-400',
    baseWinRate: 0.62,
    baseSharpe: 1.50,
    coordinationScore: 72,
    strategyBlocks: ['range-trading', 'mean-reversion', 'volatility-compression', 'momentum', 'macro-overlay'],
  },
  'volatility-architect': {
    id: 'volatility-architect',
    name: 'Volatility Architect',
    description: 'Volatility Architect is QuantLabs\' FX volatility regime engine, retuned to power high-frequency scalping by forecasting micro-volatility expansion windows. Volatility Architect identifies the precise moments when compression phases transition to ignition — the highest-probability scalping windows where breakout moves generate rapid pip capture with minimal drawdown. It dynamically adjusts the entire scalping fleet\'s aggression level based on real-time volatility phase detection, throttling trade frequency during exhaustion phases and maximizing output during ignition/expansion.',
    coreStrategy: 'Micro-volatility cycle detection for scalping regime optimization. Volatility Architect forecasts compression-to-ignition transitions for breakout scalp timing, classifies volatility phases to modulate fleet-wide trade frequency, and optimizes stop/target distances based on current ATR micro-regime. Session-volatility correlation tracking ensures scalping aggression aligns with historical session behavior.',
    market: 'forex',
    model: 'Gemini Ultra',
    icon: '🌪',
    color: 'text-violet-400',
    baseWinRate: 0.60,
    baseSharpe: 1.55,
    coordinationScore: 74,
    strategyBlocks: ['volatility-compression', 'breakout', 'momentum', 'trend-follow', 'macro-overlay'],
  },
  'adaptive-learner': {
    id: 'adaptive-learner',
    name: 'Adaptive Learning Node',
    description: 'Adaptive Learning Node is QuantLabs\' scalping evolution engine, continuously probing for new micro-edge patterns in FX price action. It tests emerging scalp signal combinations — micro-breakout timing, spread-momentum correlations, and session-specific entry optimizations — to discover new alpha sources for the high-frequency fleet. Every discovery is validated against historical scalp performance before promotion to production, ensuring the scalping system evolves without introducing fragile parameters.',
    coreStrategy: 'Experimental scalp-edge discovery with controlled validation. Adaptive Learning Node tests emerging micro-pattern relationships across FX sessions, detects edge decay in established scalp strategies, and validates new timing/entry parameter mutations. Controlled risk boundaries ensure exploration trades remain sub-1000-unit positions with tight stop-loss.',
    market: 'forex',
    model: 'Gemini 2.0',
    icon: '🧪',
    color: 'text-emerald-400',
    baseWinRate: 0.58,
    baseSharpe: 1.30,
    coordinationScore: 64,
    strategyBlocks: ['momentum', 'breakout', 'mean-reversion', 'volatility-compression', 'trend-follow'],
  },
  'sentiment-reactor': {
    id: 'sentiment-reactor',
    name: 'Sentiment Reactor',
    description: 'Sentiment Reactor is QuantLabs\' FX crowd positioning interpreter, adapted for scalping-speed sentiment analysis. It detects micro-sentiment shifts in forex positioning data — COT report deltas, retail positioning imbalances, and options skew changes — to identify contrarian scalp opportunities where crowd consensus is about to snap. Sentiment Reactor fires rapid fade signals when retail positioning becomes extreme, enabling the fleet to scalp against crowded trades with 2-8 minute hold times.',
    coreStrategy: 'Rapid contrarian scalping via positioning imbalance detection. Sentiment Reactor monitors real-time retail FX positioning ratios for extreme readings, triggers fade scalps against overcrowded directional bets, and exits within minutes as mean-reversion momentum kicks in. Pairs with highest retail concentration get priority for counter-sentiment scalps.',
    market: 'forex',
    model: 'GPT-5 Mini',
    icon: '📊',
    color: 'text-rose-400',
    baseWinRate: 0.59,
    baseSharpe: 1.40,
    coordinationScore: 68,
    strategyBlocks: ['mean-reversion', 'momentum', 'macro-overlay', 'range-trading', 'trend-follow'],
  },
  'fractal-intelligence': {
    id: 'fractal-intelligence',
    name: 'Fractal Intelligence',
    description: 'Fractal Intelligence is QuantLabs\' multi-timeframe scalp confirmation engine, examining micro-structural patterns across 1m, 5m, and 15m FX charts simultaneously. Fractal Intelligence validates scalp entries by confirming that micro price structures align with higher-timeframe momentum direction — preventing the fleet from taking counter-trend scalps that carry hidden reversal risk. It serves as the confidence-stacking layer for the scalping system, boosting conviction when fractal alignment is strong.',
    coreStrategy: 'Multi-timeframe micro-fractal confirmation for scalp validation. Fractal Intelligence checks 1m/5m/15m structural alignment before scalp entry, detects when micro-patterns diverge from higher-timeframe trend, and layers fractal confirmation scores to filter low-conviction scalps. Rapid re-evaluation occurs every 30 seconds to keep alignment data fresh for the fleet.',
    market: 'forex',
    model: 'Claude 4',
    icon: '🔬',
    color: 'text-sky-400',
    baseWinRate: 0.60,
    baseSharpe: 1.48,
    coordinationScore: 72,
    strategyBlocks: ['trend-follow', 'momentum', 'breakout', 'volatility-compression', 'range-trading'],
  },
  'risk-sentinel': {
    id: 'risk-sentinel',
    name: 'Risk Sentinel',
    description: 'Risk Sentinel is QuantLabs\' scalping-fleet risk guardian, operating as the immune system for high-frequency FX execution. Risk Sentinel monitors aggregate scalp exposure, correlation clustering across concurrent positions, drawdown velocity from rapid-fire trades, and spread-cost accumulation. In a high-volume scalping environment, Risk Sentinel is critical — preventing death-by-a-thousand-cuts scenarios where marginal losses from spread friction compound faster than gains. It enforces maximum concurrent position limits, daily loss governors, and anti-overtrading throttles.',
    coreStrategy: 'High-frequency risk surveillance with scalping-specific governors. Risk Sentinel monitors real-time aggregate exposure across all concurrent scalps, detects when spread costs are eroding edge, enforces maximum daily trade count limits, and triggers fleet-wide throttling when drawdown velocity exceeds adaptive thresholds. Position correlation monitoring prevents clustered USD-correlated scalps from creating hidden directional risk.',
    market: 'forex',
    model: 'Gemini Pro 2',
    icon: '🛡',
    color: 'text-yellow-400',
    baseWinRate: 0.63,
    baseSharpe: 1.60,
    coordinationScore: 80,
    strategyBlocks: ['macro-overlay', 'volatility-compression', 'range-trading', 'trend-follow', 'mean-reversion'],
  },
  // ═══ FX Specialist Agents ═══
  'session-momentum': {
    id: 'session-momentum',
    name: 'Session Momentum',
    description: 'Session Momentum is QuantLabs\' FX session-transition specialist, engineered to exploit the explosive momentum bursts that occur during London open, NY open, and session overlaps. It detects pre-session accumulation patterns and fires directional scalps within the first 15-45 minutes of major session opens — the highest-probability momentum window in FX markets. Session Momentum maps historical session-open behavior per pair to rank which currencies offer the cleanest breakout entries at each session boundary.',
    coreStrategy: 'Session-open breakout scalping with accumulation detection. Session Momentum identifies pre-open compression on 5m/15m charts, confirms directional bias from overnight flow, and executes breakout entries within the first candles of London/NY opens. ATR-scaled targets capture the initial momentum impulse before mean-reversion forces take hold.',
    market: 'forex',
    model: 'GPT-5',
    icon: '🔥',
    color: 'text-orange-500',
    baseWinRate: 0.66,
    baseSharpe: 1.62,
    coordinationScore: 76,
    strategyBlocks: ['breakout', 'momentum', 'volatility-compression', 'trend-follow', 'macro-overlay'],
  },
  'carry-flow': {
    id: 'carry-flow',
    name: 'Carry Flow Detector',
    description: 'Carry Flow Detector tracks institutional order flow proxies, carry trade unwinds, and central bank divergence signals to identify macro-driven FX moves before they hit retail price action. It monitors swap rate differentials, bond yield spreads, and capital flow proxies to detect when large institutional flows are building — providing directional context that elevates the scalping fleet\'s conviction on trend-aligned trades and suppresses counter-trend entries.',
    coreStrategy: 'Institutional flow detection with carry trade awareness. Carry Flow monitors interest rate differentials, sovereign yield curve movements, and cross-currency basis swaps to detect institutional positioning shifts. It generates directional bias overlays that modulate the scalping fleet\'s aggression — boosting conviction when carry alignment confirms momentum and dampening it when carry flow opposes technical signals.',
    market: 'forex',
    model: 'Gemini Pro',
    icon: '🏦',
    color: 'text-teal-400',
    baseWinRate: 0.63,
    baseSharpe: 1.52,
    coordinationScore: 74,
    strategyBlocks: ['macro-overlay', 'trend-follow', 'momentum', 'volatility-compression', 'breakout'],
  },
  'correlation-regime': {
    id: 'correlation-regime',
    name: 'Correlation Regime',
    description: 'Correlation Regime Agent monitors cross-pair correlations in real-time to prevent correlated drawdowns and identify hedged entry opportunities. It tracks dynamic correlation matrices between major/minor pairs and alerts the fleet when correlation clustering reaches dangerous levels — preventing simultaneous EUR/USD and GBP/USD longs during high-correlation regimes. It also identifies decorrelation events that create unique alpha opportunities.',
    coreStrategy: 'Dynamic correlation matrix monitoring with cluster prevention. Correlation Regime tracks rolling 20/50/100 bar correlation coefficients between all active pairs, flags when aggregate portfolio correlation exceeds danger thresholds, and recommends pair substitutions or hedge entries to maintain diversified exposure. Decorrelation breakout detection identifies regime shifts where previously correlated pairs diverge.',
    market: 'forex',
    model: 'Claude 4',
    icon: '🔗',
    color: 'text-indigo-400',
    baseWinRate: 0.61,
    baseSharpe: 1.48,
    coordinationScore: 78,
    strategyBlocks: ['macro-overlay', 'range-trading', 'volatility-compression', 'mean-reversion', 'momentum'],
  },
  'spread-microstructure': {
    id: 'spread-microstructure',
    name: 'Spread Microstructure',
    description: 'Spread Microstructure Agent is dedicated to bid-ask dynamics, liquidity depth monitoring, and optimal entry timing based on spread compression cycles. In scalping, where spreads represent a significant friction cost, this agent identifies the exact micro-windows where spreads tighten to their session minimums — enabling the fleet to enter trades with minimal friction overhead. It also detects spread blow-out events before they impact fills.',
    coreStrategy: 'Spread cycle analysis for friction-minimized entry timing. Spread Microstructure tracks rolling spread percentiles per pair per session, identifies intra-session spread compression windows (typically 30-60 min after session open), and signals optimal entry timing to the fleet. Pre-news spread widening detection prevents entries into high-friction environments. Real-time spread-to-ATR ratio monitoring ensures friction budget compliance.',
    market: 'forex',
    model: 'Gemini Flash',
    icon: '📡',
    color: 'text-lime-400',
    baseWinRate: 0.64,
    baseSharpe: 1.55,
    coordinationScore: 72,
    strategyBlocks: ['volatility-compression', 'breakout', 'momentum', 'range-trading', 'macro-overlay'],
  },
  'news-event-shield': {
    id: 'news-event-shield',
    name: 'News Event Shield',
    description: 'News Event Shield pre-filters trading activity around high-impact macro releases (NFP, ECB, FOMC, CPI) to either exploit or avoid volatility spikes. It maintains a calendar of upcoming events weighted by expected market impact, automatically widening friction gates and reducing position sizing in the 30-minute pre/post-event windows. For events with predictable volatility signatures, it can identify post-announcement scalp opportunities once initial whipsaw subsides.',
    coreStrategy: 'Economic event awareness with pre/post-event execution management. News Event Shield integrates a weighted economic calendar, classifies events by historical volatility impact per pair, and dynamically adjusts fleet-wide parameters: widening stops, reducing sizing, and increasing friction K-values during danger windows. Post-event stabilization detection identifies when whipsaw has subsided and normal scalping can resume.',
    market: 'forex',
    model: 'GPT-5 Mini',
    icon: '🛡',
    color: 'text-red-400',
    baseWinRate: 0.62,
    baseSharpe: 1.45,
    coordinationScore: 76,
    strategyBlocks: ['macro-overlay', 'volatility-compression', 'momentum', 'breakout', 'trend-follow'],
  },
  // ═══ Cross-Asset Intelligence Agents ═══
  'cross-asset-sync': {
    id: 'cross-asset-sync',
    name: 'Cross-Asset Sync',
    description: 'Cross-Asset Sync monitors inter-market relationships between FX, equities, bonds, and commodities to provide macro context for the entire trading fleet. It tracks USD/equity correlation shifts, risk-on/risk-off regime transitions via VIX-FX coupling, and commodity-currency linkages (AUD-iron ore, CAD-oil, NOK-crude) to enhance directional conviction and prevent trades that conflict with cross-asset momentum.',
    coreStrategy: 'Inter-market correlation intelligence for macro regime awareness. Cross-Asset Sync monitors DXY-equity inverse correlation strength, tracks commodity-linked currency relationships, and detects risk regime transitions via VIX-FX coupling analysis. It generates cross-asset alignment scores that modulate fleet-wide conviction — boosting signals aligned with cross-market flow and dampening conflicting entries.',
    market: 'forex',
    model: 'Gemini Ultra',
    icon: '🌍',
    color: 'text-blue-400',
    baseWinRate: 0.60,
    baseSharpe: 1.42,
    coordinationScore: 70,
    strategyBlocks: ['macro-overlay', 'trend-follow', 'momentum', 'volatility-compression', 'mean-reversion'],
  },
  'execution-optimizer': {
    id: 'execution-optimizer',
    name: 'Execution Optimizer',
    description: 'Execution Optimizer is a real-time fill quality engine that learns from every OANDA execution to continuously improve order placement. It analyzes historical fill latencies, slippage patterns by pair/session/regime, and spread behavior to recommend optimal order types, timing offsets, and price levels. It operates as the feedback loop between raw execution telemetry and the fleet\'s entry/exit mechanics — the closer to zero-slippage, the higher the scalping edge.',
    coreStrategy: 'Adaptive execution quality improvement via fill telemetry analysis. Execution Optimizer studies per-pair/per-session slippage distributions, recommends limit vs market order routing based on current conditions, and optimizes order timing offsets to minimize adverse selection. Rolling execution quality scoring feeds back into the governance state machine to trigger protective measures when fill quality degrades.',
    market: 'forex',
    model: 'Claude 3.5',
    icon: '⚙️',
    color: 'text-zinc-400',
    baseWinRate: 0.62,
    baseSharpe: 1.50,
    coordinationScore: 74,
    strategyBlocks: ['volatility-compression', 'momentum', 'breakout', 'range-trading', 'macro-overlay'],
  },
  'regime-transition': {
    id: 'regime-transition',
    name: 'Regime Transition',
    description: 'Regime Transition Agent specializes in detecting the exact inflection points where FX markets shift between trending, ranging, high-volatility, and low-liquidity states. Most trading losses cluster at regime boundaries — this agent provides early warning when the current regime is breaking down, allowing the fleet to adapt strategy weighting before the transition completes. It uses volatility structure analysis, momentum exhaustion signals, and mean-reversion probability curves to forecast regime shifts 5-15 minutes ahead.',
    coreStrategy: 'Regime change detection and early warning via structural analysis. Regime Transition monitors volatility cycle phase (compression→ignition→expansion→exhaustion), tracks momentum exhaustion signals for trend termination, and calculates mean-reversion probability curves for range-bound detection. Early regime shift warnings allow the fleet to preemptively adjust strategy block weighting — shifting from breakout to range-fade before losses accumulate.',
    market: 'forex',
    model: 'GPT-5',
    icon: '🔄',
    color: 'text-purple-400',
    baseWinRate: 0.61,
    baseSharpe: 1.46,
    coordinationScore: 76,
    strategyBlocks: ['volatility-compression', 'trend-follow', 'mean-reversion', 'breakout', 'momentum'],
  },
};
