// Governance Council Agent Configuration Registry
// 6 specialized governance agents overseeing all trading and optimization operations

export type GovernanceAgentId =
  | 'macro-oversight'
  | 'liquidity-governance'
  | 'technical-standards'
  | 'risk-compliance'
  | 'behavioral-ethics'
  | 'regulatory-alignment';

export interface GovernanceAgentDefinition {
  id: GovernanceAgentId;
  name: string;
  title: string;
  description: string;
  primaryDomain: string;
  secondaryDomain: string;
  model: string;
  icon: string;
  color: string;
  oversightScope: string;
  governanceActions: string[];
}

export const ALL_GOVERNANCE_IDS: GovernanceAgentId[] = [
  'macro-oversight',
  'liquidity-governance',
  'technical-standards',
  'risk-compliance',
  'behavioral-ethics',
  'regulatory-alignment',
];

export const GOVERNANCE_DEFINITIONS: Record<GovernanceAgentId, GovernanceAgentDefinition> = {
  'macro-oversight': {
    id: 'macro-oversight',
    name: 'Macro Oversight Governor',
    title: 'Strategic Macro Intelligence Director',
    description: 'Monitors global macroeconomic conditions and ensures all trading agents operate within sound macro regime awareness. Validates that directional conviction aligns with interest rate cycles, central bank policy shifts, and cross-border capital flow dynamics. Prevents fleet-wide exposure to macro regime transitions that could trigger correlated drawdowns.',
    primaryDomain: 'Macroeconomics',
    secondaryDomain: 'Geopolitical Risk',
    model: 'GPT-5',
    icon: '🏛',
    color: 'text-neural-purple',
    oversightScope: 'Global macro regime alignment, monetary policy impact, cross-market correlation governance',
    governanceActions: [
      'Macro regime classification audits',
      'Cross-market correlation alerts',
      'Monetary policy impact assessments',
      'Geopolitical risk escalation reviews',
    ],
  },
  'liquidity-governance': {
    id: 'liquidity-governance',
    name: 'Liquidity Governance Director',
    title: 'Market Microstructure Oversight',
    description: 'Ensures trading agents respect liquidity constraints and market microstructure realities. Monitors order flow imbalance, bid-ask spread dynamics, and institutional liquidity migration patterns to prevent agents from executing into thin liquidity environments that amplify slippage and adverse selection risk.',
    primaryDomain: 'Liquidity & Market Microstructure',
    secondaryDomain: 'Order Flow Analysis',
    model: 'Claude 4',
    icon: '🌊',
    color: 'text-neural-cyan',
    oversightScope: 'Liquidity depth monitoring, execution quality governance, slippage prevention',
    governanceActions: [
      'Liquidity depth verification',
      'Execution quality audits',
      'Slippage threshold enforcement',
      'Market impact assessments',
    ],
  },
  'technical-standards': {
    id: 'technical-standards',
    name: 'Technical Standards Auditor',
    title: 'Signal Integrity & Pattern Validation',
    description: 'Validates the statistical integrity of technical signals generated by trading agents. Audits pattern recognition accuracy, signal-to-noise ratios, and ensures that indicator-based conclusions meet minimum confidence thresholds before influencing trade decisions. Prevents agents from acting on statistically weak or degraded technical signals.',
    primaryDomain: 'Technical Indicators',
    secondaryDomain: 'Pattern Validation',
    model: 'Gemini Ultra',
    icon: '📐',
    color: 'text-neural-orange',
    oversightScope: 'Signal quality validation, indicator integrity, statistical confidence enforcement',
    governanceActions: [
      'Signal quality score audits',
      'Pattern reliability assessments',
      'Indicator degradation alerts',
      'Confidence threshold enforcement',
    ],
  },
  'risk-compliance': {
    id: 'risk-compliance',
    name: 'Risk Compliance Marshal',
    title: 'Portfolio Risk & Exposure Governance',
    description: 'Enforces portfolio-level risk compliance across all trading and optimization agents. Monitors aggregate exposure, drawdown acceleration, correlation clustering, and position concentration to ensure the fleet operates within defined risk stability anchors. Acts as the final checkpoint before any trade receives system-wide clearance.',
    primaryDomain: 'Risk Management',
    secondaryDomain: 'Portfolio Exposure',
    model: 'GPT-5',
    icon: '⚖',
    color: 'text-neural-green',
    oversightScope: 'Drawdown containment, exposure limits, correlation risk, position sizing compliance',
    governanceActions: [
      'Drawdown ceiling enforcement',
      'Exposure concentration audits',
      'Correlation clustering alerts',
      'Position sizing compliance checks',
    ],
  },
  'behavioral-ethics': {
    id: 'behavioral-ethics',
    name: 'Behavioral Ethics Monitor',
    title: 'Crowd Psychology & Sentiment Integrity',
    description: 'Monitors behavioral finance dynamics and ensures trading agents do not become trapped in crowd psychology feedback loops. Validates that sentiment-driven signals maintain contrarian objectivity and that herd behavior detection remains calibrated. Prevents emotional momentum from overriding quantitative discipline.',
    primaryDomain: 'Behavioral Finance',
    secondaryDomain: 'Sentiment Integrity',
    model: 'Gemini Pro 2',
    icon: '🧠',
    color: 'text-rose-400',
    oversightScope: 'Sentiment calibration oversight, herd behavior detection, contrarian signal validation',
    governanceActions: [
      'Sentiment bias audits',
      'Herd behavior detection alerts',
      'Contrarian signal validation',
      'Emotional momentum dampening',
    ],
  },
  'regulatory-alignment': {
    id: 'regulatory-alignment',
    name: 'Regulatory Alignment Sentinel',
    title: 'Market Structure & Compliance Assurance',
    description: 'Ensures all fleet operations align with market structure rules, trading hour constraints, and regulatory best practices. Monitors for potential market manipulation patterns, wash trading signatures, and ensures trade timing respects exchange-specific session rules and circuit breaker protocols.',
    primaryDomain: 'Regulatory Compliance',
    secondaryDomain: 'Market Structure Rules',
    model: 'Claude 3.5',
    icon: '📜',
    color: 'text-amber-400',
    oversightScope: 'Regulatory alignment, market structure compliance, trading hour enforcement',
    governanceActions: [
      'Trading session compliance checks',
      'Market manipulation pattern scans',
      'Circuit breaker protocol monitoring',
      'Best execution verification',
    ],
  },
};
